// <auto-generated />
using System;
using ChatService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatService.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChatService.Models.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ChatRoomType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("ChatRooms");

                    b.HasDiscriminator<string>("ChatRoomType").HasValue("ChatRoom");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ChatService.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("ChatService.Models.GroupChatMember", b =>
                {
                    b.Property<int>("GroupChatRoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("GroupChatRoomId", "UserId");

                    b.ToTable("GroupChatMembers");
                });

            modelBuilder.Entity("ChatService.Models.UserChatRoom", b =>
                {
                    b.Property<int>("PrivateChatRoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PrivateChatRoomId", "UserId");

                    b.ToTable("UserChatRooms");
                });

            modelBuilder.Entity("ChatService.Models.GroupChatRoom", b =>
                {
                    b.HasBaseType("ChatService.Models.ChatRoom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("ChatService.Models.PrivateChatRoom", b =>
                {
                    b.HasBaseType("ChatService.Models.ChatRoom");

                    b.HasDiscriminator().HasValue("Private");
                });

            modelBuilder.Entity("ChatService.Models.ChatRoom", b =>
                {
                    b.HasOne("ChatService.Models.Folder", "Folder")
                        .WithMany("ChatRooms")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ChatService.Models.GroupChatMember", b =>
                {
                    b.HasOne("ChatService.Models.GroupChatRoom", "GroupChatRoom")
                        .WithMany("GroupChatMembers")
                        .HasForeignKey("GroupChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChatRoom");
                });

            modelBuilder.Entity("ChatService.Models.UserChatRoom", b =>
                {
                    b.HasOne("ChatService.Models.PrivateChatRoom", "PrivateChatRoom")
                        .WithMany("UserChatRooms")
                        .HasForeignKey("PrivateChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateChatRoom");
                });

            modelBuilder.Entity("ChatService.Models.Folder", b =>
                {
                    b.Navigation("ChatRooms");
                });

            modelBuilder.Entity("ChatService.Models.GroupChatRoom", b =>
                {
                    b.Navigation("GroupChatMembers");
                });

            modelBuilder.Entity("ChatService.Models.PrivateChatRoom", b =>
                {
                    b.Navigation("UserChatRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
